language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      env: QT_BASE=512 CXX_COMPILER=g++-8 C_COMPILER=gcc-8 BUILD_TYPE=Release
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-8
          - g++-8

before_install:
  - if [ "$QT_BASE" = "512" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y; fi
  - sudo apt-get update -qq

install:
  - if [ "$QT_BASE" = "512" ]; then sudo apt-get install -qq qt512base qt512connectivity qt512multimedia qt512svg qt512translations qt512tools qt512webchannel qt512webengine ; source /opt/qt512/bin/qt512-env.sh ; export QTHOME=/opt/qt512 ; fi

  # cmake
  - curl -o cmake.tar.gz -O https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.tar.gz
  - mkdir /opt/cmake
  - tar -xf cmake.tar.gz -C /opt/cmake --strip-components=1
  - rm -f cmake.tar.gz
  - export PATH=/opt/cmake/bin:/opt/qt512/bin:${PATH}
  - export CMAKE_PREFIX_PATH=/opt/qt512:${CMAKE_PREFIX_PATH}

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - ${CXX_COMPILER} --version
  - ${C_COMPILER} --version
  - cmake -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DENABLE_TESTING=ON ..

script:
  - cmake --build .
  - make test

